### PR TITLE
Don't try to verify metapackages

### LINKED ISSUE #103: Do not download dist file targets for metapackages
```
Installation failed, reverting ./composer.json and ./composer.lock to their original content.

In ComposerRepository.php line 1450:
                                                                                                                                                                                                                   
  Could not load packages drupal/core-recommended in composer repo (https://signed-packagist.staging.devdrupal.org/) from cached file (provider-drupal~core-recommended.json originating from https://signed-packa/  
  gist.staging.devdrupal.org/p2/drupal/core-recommended.json): [Tuf\Exception\NotFoundException] Target not found: drupal/core-recommended/10.2.2.0                                                                
                                                                                                                                                                                                                   

In ComposerCompatibleUpdater.php line 64:
                                                      
  Target not found: drupal/core-recommended/10.2.2.0  
                                                      

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>…]
```

This is caused by `drupal/core-recommended/10.2.2.0` not being something that should be processed or downloaded because Composer metapackages are special.

* Documented at https://github.com/composer/composer/blob/11e5237ad9d9e8f29bdc57d946f87c816320d863/doc/07-runtime.md?plain=1#L110
* Implemented at https://github.com/composer/composer/blob/11e5237ad9d9e8f29bdc57d946f87c816320d863/src/Composer/Installer/MetapackageInstaller.php#L59

Our mirror for `drupal/*` packages on Packagist.org uses Satis, which uses Composer to decide what to download. So it does not download dist files for metapackages. This means we don't mirror those and they do not get signed as targets. `dist` data is present in the composer json files, but those are pretty much vestigial. This shows up as https://signed-packagist.staging.devdrupal.org/p2/drupal/core-recommended.json not having rewritten the URLs from GitHub.

### Solution

The quick solution would be to add `if (metapackage) { skip looking at dist }` to the right place.

A more-correct solution might be using https://github.com/composer/composer/blob/11e5237ad9d9e8f29bdc57d946f87c816320d863/src/Composer/Installer/MetapackageInstaller.php#L59 in some way to not hard-code metapackage behavior, and anything similar found.

### PR DESCRIPTION
**Pull request by phenaproxima**
Fixes #103.

### CODE REVIEW

File: src/TufValidatedComposerRepository.php [hunk 1]
```diff
@@ -173,12 +173,18 @@ protected function configurePackageTransportOptions(PackageInterface $package):
...
      *   Whether PHP-TUF is enabled for this repository.
      */
-    private function isTufEnabled(): bool
+    private function isTufEnabled(?PackageInterface $package = null): bool
     {
-        return $this->updater instanceof ComposerCompatibleUpdater;
+        // Metapackages are not downloaded into the code base at all, so don't
+        // bother validating them.
+        // @see https://github.com/composer/composer/blob/11e5237ad9d9e8f29bdc57d946f87c816320d863/doc/07-runtime.md?plain=1#L110
+        return $this->updater instanceof ComposerCompatibleUpdater && $package?->getType() !== 'metapackage';
```
Comment (tedbow) [inline src/TufValidatedComposerRepository.php:187]: So the meta package must at least have composer.json, or something else to specify what packages it needs. Is that downloaded to inspect it?

Comment (phenaproxima) [reply src/TufValidatedComposerRepository.php:187]: Well, all Composer packages must have a composer.json, metapackage or no.

And yes, it's getting downloaded -- I updated the tests to confirm that. As you can see, we still install Pathauto and Token, but we install them _via the metapackage_ rather than individually. That pretty much proves it works.

**Review by tedbow — APPROVED** [review]
Looks good!
